import Foundation

public struct FlutterProjectRule: ScanRule {
    public let id: String
    public let displayName: String
    public let toolchain: String
    private let projectRoot: URL
    private let fileManager: FileManager

    public init(projectRoot: URL, fileManager: FileManager = .default) {
        self.id = "flutter-project"
        self.displayName = "Flutter project storage"
        self.toolchain = "Flutter / Dart / FVM"
        self.projectRoot = projectRoot
        self.fileManager = fileManager
    }

    public func scan(measurer: FileSizeMeasurer) -> [StorageItem] {
        guard fileManager.fileExists(atPath: projectRoot.appendingPathComponent("pubspec.yaml").path) else {
            return [StorageItem(
                id: "flutter-project-unsupported:\(projectRoot.path)",
                displayName: "Flutter project",
                path: projectRoot.path,
                category: .manualReview,
                toolchain: toolchain,
                sizeBytes: nil,
                riskLevel: .unsupported,
                status: .unsupported,
                defaultSelected: false,
                explanation: "No pubspec.yaml was found at this project root.",
                exception: ScanException(
                    type: .unsupportedCacheRule,
                    operation: "scan",
                    message: "The selected folder is not recognized as a Flutter project: \(projectRoot.path)",
                    suggestion: "Select a folder containing pubspec.yaml."
                )
            )]
        }

        let candidates: [(String, URL, StorageCategory, RiskLevel, String)] = [
            (
                "Flutter build directory",
                projectRoot.appendingPathComponent("build"),
                .buildArtifact,
                .medium,
                "Generated build artifacts. Cleanup triggers a full rebuild."
            ),
            (
                "Flutter Dart tool directory",
                projectRoot.appendingPathComponent(".dart_tool"),
                .buildArtifact,
                .medium,
                "Generated Dart tooling state. Cleanup triggers package and build regeneration."
            ),
            (
                "Flutter iOS Pods",
                projectRoot.appendingPathComponent("ios/Pods"),
                .dependencyStore,
                .medium,
                "Native iOS dependencies may need to be installed again."
            ),
            (
                "Flutter Android Gradle",
                projectRoot.appendingPathComponent("android/.gradle"),
                .buildArtifact,
                .medium,
                "Android Gradle state can be regenerated by Gradle."
            ),
            (
                "Flutter Android app build",
                projectRoot.appendingPathComponent("android/app/build"),
                .buildArtifact,
                .medium,
                "Android app build products can be regenerated."
            ),
            (
                "Flutter OHOS build",
                projectRoot.appendingPathComponent("ohos/build"),
                .buildArtifact,
                .medium,
                "HarmonyOS build products can be regenerated."
            ),
            (
                "Flutter HarmonyOS build",
                projectRoot.appendingPathComponent("harmonyos/build"),
                .buildArtifact,
                .medium,
                "HarmonyOS build products can be regenerated."
            ),
            (
                "Flutter package outputs",
                projectRoot.appendingPathComponent("build/app/outputs"),
                .packageOutput,
                .manualReview,
                "Generated package outputs may be needed for QA, upload, or release history."
            )
        ]

        return candidates.map { name, path, category, risk, explanation in
            switch measurer.measure(url: path) {
            case .success(let size):
                return StorageItem(
                    id: "flutter-project:\(path.path)",
                    displayName: name,
                    path: path.path,
                    category: category,
                    toolchain: toolchain,
                    sizeBytes: size,
                    riskLevel: risk,
                    status: .found,
                    defaultSelected: false,
                    explanation: explanation,
                    exception: nil
                )
            case .failure(let exception):
                return StorageItem(
                    id: "flutter-project:\(path.path)",
                    displayName: name,
                    path: path.path,
                    category: category,
                    toolchain: toolchain,
                    sizeBytes: nil,
                    riskLevel: risk,
                    status: exception.type == .pathNotFound ? .missing : .failed,
                    defaultSelected: false,
                    explanation: explanation,
                    exception: exception
                )
            }
        }
    }
}
