import XCTest
@testable import DevStorageCore

final class ModelEncodingTests: XCTestCase {
    func testStorageItemEncodesStableJSONFields() throws {
        let item = StorageItem(
            id: "flutter-build:/tmp/App/build",
            displayName: "Flutter build artifacts",
            path: "/tmp/App/build",
            category: .buildArtifact,
            toolchain: "Flutter / Dart / FVM",
            sizeBytes: 128,
            riskLevel: .medium,
            status: .found,
            defaultSelected: false,
            explanation: "Can be regenerated by a full Flutter build.",
            exception: nil
        )

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        let data = try encoder.encode(item)
        let json = String(decoding: data, as: UTF8.self)

        XCTAssertTrue(json.contains(#""category":"buildArtifact""#))
        XCTAssertTrue(json.contains(#""riskLevel":"medium""#))
        XCTAssertTrue(json.contains(#""status":"found""#))
        XCTAssertTrue(json.contains(#""sizeBytes":128"#))
    }

    func testStorageItemCanCarryNamedException() throws {
        let exception = ScanException(
            type: .permissionDenied,
            operation: "measure",
            message: "The folder could not be read.",
            suggestion: "Grant Full Disk Access or exclude this path."
        )

        let item = StorageItem(
            id: "xcode-derived-data:/restricted",
            displayName: "Xcode DerivedData",
            path: "/restricted",
            category: .cache,
            toolchain: "Xcode / iOS",
            sizeBytes: nil,
            riskLevel: .low,
            status: .failed,
            defaultSelected: false,
            explanation: "Xcode build cache.",
            exception: exception
        )

        XCTAssertEqual(item.exception?.type, .permissionDenied)
        XCTAssertEqual(item.status, .failed)
    }
}
